server.port=${SERVER_PORT:0}

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:5MB}

spring.application.name=file-storage

spring.flyway.schemas=${FILE_STORAGE_DB_SCHEMA:file_storage}
spring.flyway.default-schema=${FILE_STORAGE_DB_SCHEMA:file_storage}
spring.jpa.properties.hibernate.default_schema=${FILE_STORAGE_DB_SCHEMA:file_storage}

file-storage.path=${FILE_STORAGE_PATH:./file-storage/attachments}

spring.config.import=optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}